# Generated by Django 4.0 on 2023-12-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_name',
            field=models.CharField(choices=[('pb1', 'Publication 1'), ('pb2', 'Publication 2'), ('pb3', 'Publication 3')], max_length=3, null=True),
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
