# Generated by Django 4.0 on 2023-12-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_publication_name_alter_book_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_name',
        ),
    ]
